{% set name = "pyworkdir" %}
{% set version = "0.3.0" %}
{% set sha256 = "ebe639bbe3c771467a68a80cde2ddb7b2e4dfe5e31b0fc6b8e3925c08895fb61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/olllom/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - jinja2
    - pyyaml
  run:
    - python >=3.6
    - jinja2
    - pyyaml

test:
  imports:
    - pyworkdir

about:
  home: http://github.com/olllom/pyworkdir
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python working directories'
  description: Python working directories
  doc_url: http://pyworkdir.readthedocs.io/
  dev_url: https://github.com/olllom/pyworkdir

extra:
  recipe-maintainers:
    - olllom
